# Cocktail Bot Configuration Example
# Make a copy of this file as config.yaml and update the values

# Log level (debug, info, warn, error)
log_level: info

# Telegram settings
telegram:
  # Bot token (get from BotFather)
  token: "7468147182:AAHQn-nGWxcHyOwiSug82JvpZWhX1C6ZgP4"
  # Bot username
  user: "test_cocktail_redemption_bot"

# Database settings
database:
  # Database type (csv, sqlite, googlesheet, postgresql, mysql, mongodb)
  type: "sqlite"
  # Connection string or path
  connection_string: "./data/users.sqlite"
  # For googlesheet connection string is "https://docs.google.com/spreadsheets/d/1234567890/edit#gid=0"
  # -> https://docs.google.com/spreadsheets/d/1DttA5fdJiJTOChVewghcTMthDPoMa9Q655LxVBw0eVA/edit
  # For csv and sqlite it is path to the csv/database file
  # For googlesheet it is the url of the spreadsheet
  # For postgresql it is the connection string
  # For mysql it is the connection string
  # For mongodb it is the connection string

# Rate limiting settings
rate_limiting:
  # Maximum requests per minute per user
  requests_per_minute: 10
  # Maximum requests per hour per user
  requests_per_hour: 100
