services:
  cocktail-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: ceesaxp/cocktail-bot:latest
    container_name: cocktail-bot
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data:/app/data
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - cocktail-net

  # Uncomment this service if you want to use PostgreSQL as your database
  # postgres:
  #   image: postgres:15-alpine
  #   container_name: cocktail-postgres
  #   environment:
  #     POSTGRES_DB: cocktailbot
  #     POSTGRES_USER: botuser
  #     POSTGRES_PASSWORD: botpassword
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped
  #   networks:
  #     - cocktail-net

  # Uncomment this service if you want to use MongoDB as your database
  # mongodb:
  #   image: mongo:6-jammy
  #   container_name: cocktail-mongodb
  #   environment:
  #     MONGO_INITDB_DATABASE: cocktailbot
  #     MONGO_INITDB_ROOT_USERNAME: botuser
  #     MONGO_INITDB_ROOT_PASSWORD: botpassword
  #   volumes:
  #     - mongodb-data:/data/db
  #   ports:
  #     - "27017:27017"
  #   restart: unless-stopped
  #   networks:
  #     - cocktail-net

networks:
  cocktail-net:
    driver: bridge

volumes:
  postgres-data:
  mongodb-data:
